import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import path from 'node:path';import {reviewWorld} from './helpers/review-world.mjs';import {universalWorld} from './helpers/startup-world.mjs';
const prepare=async()=>{const w=reviewWorld();await w.api.campaignMentionEvidence.sync({rescan:true});await w.api.campaignRelationshipEvidence.sync();w.scheduled.clear();for(const key of Object.keys(w.counts))w.counts[key]=0;return w;};
for(const mode of ['choose','create'])test(`${mode}: saved decision reuses narrative candidates`,async()=>{
 const w=await prepare();let scans=0;const base=w.api.campaignNewEntityDiscovery.scan;
 w.api.campaignNewEntityDiscovery={...w.api.campaignNewEntityDiscovery,scan:async options=>{scans++;return base(options);}};
 await w.act(mode);assert.deepEqual(w.errors,[]);assert.equal(scans,0);
 assert.ok(w.api.campaignMentionEvidence.recordsForSource(w.session.uuid).some(row=>row.targetUuid));
});
for(const mode of ['choose','create','keep'])test(`${mode}: one final render, no full campaign analysis, bounded graph/index`,async()=>{
 const w=await prepare(),builds=w.api.entityIntelligence.diagnostics().builds;await w.act(mode);await w.drain();assert.deepEqual(w.errors,[]);assert.equal(w.counts.fullScans,0);assert.equal(w.counts.renders,1);assert.equal(w.counts.JournalEntryPage,0);assert.ok(w.counts.JournalEntry<=2);assert.ok(w.counts.analysisRuns<=2);assert.equal(w.context.AdventurersTomeReviewDecision.snapshot().stages['relationship-graph'].counters.graphBuilds,1);assert.equal(w.api.entityIntelligence.diagnostics().builds-builds,1);
});
test('Link persists one selected canonical identity and refreshes its source Memory',async()=>{const w=await prepare();await w.act('choose');assert.equal(w.api.campaignReviewLearning.decisionFor('Vale',{sourceUuid:w.session.uuid}).targetUuid,w.target.uuid);assert.equal(w.api.campaignEntityLinks.hasCanonicalLink({sourceUuid:w.session.uuid,targetUuid:w.target.uuid}),true);assert.ok(w.api.campaignMentionEvidence.recordsForSource(w.session.uuid).some(row=>row.mentionText==='Vale'&&row.targetUuid===w.target.uuid));});
test('Create creates exactly one entity, links it and resolves Review',async()=>{const w=await prepare(),before=w.game.journal.contents.length;await w.act('create');assert.equal(w.game.journal.contents.length,before+1);const decision=w.api.campaignReviewLearning.decisionFor('Vale',{sourceUuid:w.session.uuid});assert.equal(decision.action,'created');assert.ok(w.api.campaignEntityLinks.hasCanonicalLink({sourceUuid:w.session.uuid,targetUuid:decision.targetUuid}));assert.ok(w.api.campaignMentionEvidence.recordsForSource(w.session.uuid).some(row=>row.outcome==='CREATED'));});
test('Scoped Review refresh cannot automatically create a second identity from the source',async()=>{const w=await prepare(),base=w.api.campaignEntityCreation.resolveCandidates;let optionsSeen;w.api.campaignEntityCreation={...w.api.campaignEntityCreation,resolveCandidates:async(rows,options)=>{optionsSeen=options;return base(rows,options);}};await w.act('choose');assert.equal(optionsSeen.allowCreate,false);const before=w.game.journal.contents.length;const rows=await base([{text:'Mira Copper',id:'other',sourceJournalUuid:w.session.uuid,sourcePageUuid:w.page.uuid,classification:{kind:'character',confidence:.99,signals:['person-role-apposition']},detection:{score:.99}}],{allowCreate:false});assert.equal(rows[0].outcome,'REVIEW');assert.equal(w.game.journal.contents.length,before);});
test('Keep unresolved runs zero narrative analyses and retains source-scoped dismissal',async()=>{const w=await prepare();await w.act('keep');assert.equal(w.counts.analysisRuns,0);assert.equal(w.api.campaignReviewLearning.decisionFor('Vale',{sourceUuid:w.session.uuid}).action,'source-ignored');});
for(const mode of ['choose','create'])test(`${mode}: simultaneous clicks do not duplicate identity/link writes`,async()=>{const w=await prepare(),before=w.game.journal.contents.length;await Promise.all([w.act(mode),w.act(mode)]);assert.equal(w.game.journal.contents.length-before,mode==='create'?1:0);assert.equal(w.counts.renders,1);assert.ok(w.counts.JournalEntry<=2);});
test('Unrelated source Memory records remain byte-identical after scoped refresh',async()=>{const w=await prepare(),other=w.game.journal.contents.find(doc=>doc.name==='Source 1'),before=JSON.stringify(w.api.campaignMentionEvidence.recordsForSource(other.uuid));await w.act('choose');assert.equal(JSON.stringify(w.api.campaignMentionEvidence.recordsForSource(other.uuid)),before);});
test('Unrelated source relationships and decisions survive scoped refresh',async()=>{const w=await prepare(),key='campaignRelationshipEvidenceV1';const before=JSON.parse(w.storage.get(key));before.evidence.push({id:'unrelated',sourceUuid:w.game.journal.contents.find(doc=>doc.name==='Source 1').uuid,active:true,subjectUuid:w.person.uuid,objectUuid:w.group.uuid,relationType:'knows'});before.decisions.push({evidenceId:'unrelated',action:'confirm'});w.storage.set(key,JSON.stringify(before));await w.act('choose');const after=JSON.parse(w.storage.get(key));assert.deepEqual(after.evidence.find(row=>row.id==='unrelated'),before.evidence.at(-1));assert.deepEqual(after.decisions,before.decisions);});
test('Authoritative decision survives failed derived refresh',async()=>{const w=await prepare();w.api.campaignRelationshipEvidence={...w.api.campaignRelationshipEvidence,sync:async()=>{throw Error('Derived failure');}};await w.act('choose');assert.equal(w.api.campaignReviewLearning.decisionFor('Vale',{sourceUuid:w.session.uuid}).targetUuid,w.target.uuid);assert.equal(w.counts.renders,1);assert.deepEqual(w.errors,[]);});
test('Saved creation and Undo remain available if incremental discovery refresh fails',async()=>{const w=await prepare();w.api.discovery={...w.api.discovery,refreshDocument:async()=>{throw Error('Derived view failure');}};await w.act('create');assert.deepEqual(w.errors,[]);assert.equal(w.app._lastCampaignDecision.mode,'create');assert.equal(w.api.campaignReviewLearning.decisionFor('Vale',{sourceUuid:w.session.uuid}).action,'created');});
test('Failed decision persistence rolls back a newly added canonical link',async()=>{const w=await prepare();w.api.campaignReviewLearning={...w.api.campaignReviewLearning,chooseForSource:async()=>{throw Error('Persistence failure');}};await w.act('choose');assert.equal(w.api.campaignEntityLinks.hasCanonicalLink({sourceUuid:w.session.uuid,targetUuid:w.target.uuid}),false);assert.equal(w.app._campaignDecisionPending,false);assert.equal(w.context.AdventurersTomeReviewDecision.isActive(),false);});
test('Undo removes only the new link and allows a later decision',async()=>{const w=await prepare();await w.act('choose');await w.undo();assert.equal(w.api.campaignEntityLinks.hasCanonicalLink({sourceUuid:w.session.uuid,targetUuid:w.target.uuid}),false);await w.act('choose');assert.equal(w.api.campaignEntityLinks.hasCanonicalLink({sourceUuid:w.session.uuid,targetUuid:w.target.uuid}),true);});
test('Undo keeps an existing link intact',async()=>{const w=await prepare();await w.api.campaignEntityLinks.linkCanonical({sourceUuid:w.session.uuid,targetUuid:w.target.uuid});await w.act('choose');await w.undo();assert.equal(w.api.campaignEntityLinks.hasCanonicalLink({sourceUuid:w.session.uuid,targetUuid:w.target.uuid}),true);});
test('Create Undo clears the source decision/link while preserving the authored identity',async()=>{const w=await prepare();await w.act('create');const decision=w.api.campaignReviewLearning.decisionFor('Vale',{sourceUuid:w.session.uuid});await w.undo();assert.ok(w.docs.has(decision.targetUuid));assert.equal(w.api.campaignEntityLinks.hasCanonicalLink({sourceUuid:w.session.uuid,targetUuid:decision.targetUuid}),false);assert.equal(w.api.campaignReviewLearning.decisionFor('Vale',{sourceUuid:w.session.uuid}).action,'source-ignored');});
test('Full manual reanalysis retains the selected identity',async()=>{const w=await prepare();await w.act('choose');await w.api.campaignMentionEvidence.sync({rescan:true});assert.equal(w.api.campaignReviewLearning.decisionFor('Vale',{sourceUuid:w.session.uuid}).targetUuid,w.target.uuid);assert.ok(w.api.campaignMentionEvidence.recordsForSource(w.session.uuid).some(row=>row.targetUuid===w.target.uuid));});
test('Learning reload preserves authoritative decision',async()=>{const w=await prepare();await w.act('choose');w.reload('campaign-review-learning.js');assert.equal(w.api.campaignReviewLearning.decisionFor('Vale',{sourceUuid:w.session.uuid}).targetUuid,w.target.uuid);});
test('Player cannot execute a Review action or inspect GM Review telemetry',async()=>{const w=await prepare();await w.act('choose');w.game.user.isGM=false;const before=w.counts.JournalEntry;await w.act('create');assert.equal(w.counts.JournalEntry,before);assert.equal(w.context.AdventurersTomeReviewDecision.snapshot(),null);});
test('Telemetry contains no candidate/source/target names or UUIDs',async()=>{const w=await prepare();await w.act('choose');const text=JSON.stringify(w.context.AdventurersTomeReviewDecision.snapshot());for(const secret of ['Vale','Copper Watch',w.session.uuid,w.target.uuid])assert.ok(!text.includes(secret));});
test('Legitimate external page edits retain their scheduled scan during a decision',async()=>{const w=await prepare(),base=w.api.campaignReviewLearning.chooseForSource;w.api.campaignReviewLearning={...w.api.campaignReviewLearning,chooseForSource:async options=>{w.page.text.content+=' The scouts return tomorrow.';w.context.Hooks.callAll('updateJournalEntryPage',w.page,{'text.content':w.page.text.content},{});return base(options);}};await w.act('choose');assert.ok(w.scheduled.size>0);await w.drain();assert.ok(w.counts.fullScans>0);});
test('Per-source discovery merge retains unrelated sources in its snapshot',async()=>{const w=await prepare();const before=w.api.campaignNewEntityDiscovery.snapshot().candidates.filter(row=>row.sourceJournalUuid!==w.session.uuid);await w.act('choose');assert.deepEqual(w.api.campaignNewEntityDiscovery.snapshot().candidates.filter(row=>row.sourceJournalUuid!==w.session.uuid),before);});
test('Real Universal registry/discovery refresh one created canonical document without a world rebuild',async()=>{
 const w=await prepare();universalWorld(w);w.api.app=()=>w.app;const hooks=w.context.Hooks;w.context.Hooks={...hooks,once:(event,fn)=>{if(event==='ready')fn();}};
 const file=path.resolve(import.meta.dirname,'../scripts/universal-campaign-discovery.js');vm.runInContext(`{${fs.readFileSync(file,'utf8').replace(/^import .*;\r?\n/gm,'')}}`,w.context);w.context.Hooks=hooks;
 await w.api.discovery.scan({includeCompendiums:false});w.scheduled.clear();const before=w.profiler.snapshot().stages.find(row=>row.phase==='universal-registry').counters.fullWorldScans;
 await w.act('create');await w.drain();assert.deepEqual(w.errors,[]);const target=w.api.campaignReviewLearning.decisionFor('Vale',{sourceUuid:w.session.uuid}).targetUuid;assert.ok(w.api.discovery.snapshot().entities.some(entity=>entity.canonicalUuid===target));assert.ok(w.api.universalDocuments.resolve(target));assert.equal(w.profiler.snapshot().stages.find(row=>row.phase==='universal-registry').counters.fullWorldScans,before);assert.equal(w.counts.fullScans,0);
});
test('Review stage durations are finite and render/hook wrappers are restored on completion',async()=>{const w=await prepare(),render=w.app.render,dispatch=w.context.Hooks.callAll;await w.act('choose');for(const stage of Object.values(w.context.AdventurersTomeReviewDecision.snapshot().stages))assert.ok(Number.isFinite(stage.ms));assert.equal(w.app.render,render);assert.equal(w.context.Hooks.callAll,dispatch);});
test('External Universal document updates are deferred rather than discarded during a decision',async()=>{const w=await prepare();universalWorld(w);w.scheduled.clear();const base=w.api.campaignReviewLearning.chooseForSource;w.api.campaignReviewLearning={...w.api.campaignReviewLearning,chooseForSource:async options=>{w.target.name='Externally edited';w.context.Hooks.callAll('updateJournalEntry',w.target,{name:w.target.name},{});return base(options);}};await w.act('choose');assert.ok(w.scheduled.size>0);});
